---
# -----------------------------------------------------------------------------
# Set DB2 SSL Port (cp4d_db_ssl_port) into Facts
# -----------------------------------------------------------------------------
- name: Get the k8s Service info of DB2 database {{ db2wh_instance_name }}
  community.kubernetes.k8s_info:
    api_version: v1
    kind: Service
    name: "{{ db2_svc_name }}"
    namespace: "{{ cpd_meta_namespace }}"
  register: cp4d_db2_service_info

# - debug: var=cp4d_db2_service_info

- set_fact:
    cp4d_db_port_list: "{{ cp4d_db2_service_info.resources[0].spec.ports }}"

<<<<<<< HEAD:ibm/mas_devops/roles/cp4d_db2wh/tasks/cpd35/get_db2_ssl_port.yml
# - debug:
#     msg: "{{ cp4d_db_port_list }}"

- name: Get the SSL port of DB2 database {{ db2wh_instance_name }} from k8s Service info
=======
- name: Get the SSL port of DB2 database {{ db2wh_instance_name }} from k8s Service info
  debug:
    msg: "{{ cp4d_db_port_list | json_query(querystring) }}"
>>>>>>> f312435c261db29f3ee6d62fb5203245e71de4df:ibm/mas_devops/roles/cp4d_db2wh/tasks/get_db2_ssl_port.yml
  vars:
    db2wh_ports: "{{ item }}"
  set_fact: 
    sslNodePort: "{{ item.port }}"
  when: item.name == 'ssl-server'
  with_items: "{{ cp4d_db_port_list }}"

# - debug:
#     msg: "NodePort: {{ sslNodePort }}"

- set_fact:
    cp4d_db_ssl_port: "{{ sslNodePort }}"