---
# 0. Check for undefined properties that do not have a default
# -----------------------------------------------------------------------------
# - fail if cpd_version is not provided
- name: "Fail if cpd_version is not provided"
  when:
    - cpd_version is not defined or cpd_version == ''
  fail:
    msg: "cpd_version is required"

# 1. Load var files
# -----------------------------------------------------------------------------
- name: Load variables
  include_vars: "defaults/{{ cpd_version }}/main.yml"

- name: Provision DB2 instance
  include_tasks: "tasks/{{ cpd_version }}/provision-instance.yml"
