
---
# We'll just set a flag to indicate we need CIS webhook reinstalled in new ibm-common-services namespace via 'mas_devops.suite_dns' role
- name: "Set fact: 'isSuiteUpgrade: true'"
  set_fact:
    isSuiteUpgrade: true

- debug:
    msg: "Setting 'isSuiteUpgrade': 'true', this will allow CIS webhook reinstall under {{ common_services_namespace }}."
