
---
# If custom_cluster_issuer is not provided.
# The list of resources to be copied are:
# secret/{{ mas_instance_id }}-cert-public-ca
# secret/{{ mas_instance_id }}-cert-internal-ca
# issuer.cert-manager.io/mas-{{ mas_instance_id }}-core-internal-ca-issuer
# issuer.cert-manager.io/mas-{{ mas_instance_id }}-core-public-ca-issuer
# certificate.cert-manager.io/{{ mas_instance_id }}-cert-internal-ca
# certificate.cert-manager.io/{{ mas_instance_id }}-cert-public-ca

# Copy Default Public CA Issuer resources from cert-manager namespace
# -------------------------------------------------------------------------------------------------
# These resources will only exist if the user didn't provide their own ClusterIssuer
- name: "Public CA Issuer : Copy {{ mas_namespace }}-public-ca-issuer"
  include_tasks: tasks/cert_manager_upgrade/copy_issuer.yml
  vars:
    source_issuer_name: "{{ mas_namespace }}-public-ca-issuer"
    source_issuer_secret_name: "{{ cert_names.public_ca }}"
    source_certificate_name: "{{ cert_names.public_ca }}"
