
---
# If mas_custom_cluster issuer is provided, we'll be copying all 
# resources releated to CIS / Let's encrypt webhook resources
# The list of resources to be copied are:

# secret/cert-manager-webhook-ibm-cis-dockercfg-6wrv6
# secret/cert-manager-webhook-ibm-cis-root-ca-certificate
# secret/cert-manager-webhook-ibm-cis-serving-cert
# secret/cert-manager-webhook-ibm-cis-token-4qzqb
# secret/cert-manager-webhook-ibm-cis-token-z9t2h
# secret/cis-api-key
# secret/cis-letsencrypt-production-account-key
# secret/cis-letsencrypt-staging-account-key
# issuer.cert-manager.io/cert-manager-webhook-ibm-cis-root-ca-issuer
# issuer.cert-manager.io/cert-manager-webhook-ibm-cis-self-signed-issuer
# certificate.cert-manager.io/cert-manager-webhook-ibm-cis-root-ca-certificate
# certificate.cert-manager.io/cert-manager-webhook-ibm-cis-serving-cert

# Copy all resources created by Webhook IBM CIS under cert-manager namespace
# -------------------------------------------------------------------------------------------------
# - name: "Webhook IBM CIS Secrets : Lookup all ibm-cis related secrets"
#   shell: oc get secrets -n {{ cert_manager_namespace }} | grep cis- | awk '{print $1}'
#   register: cis_secrets_output
#   failed_when: cis_secrets_output.stdout_lines | length == 0

# - set_fact:
#     list_of_cis_secrets: "{{ cis_secrets_output.stdout_lines }}"

# - debug:
#     msg: "List of Webhook IBM CIS Secrets to be copied: {{ list_of_cis_secrets }}"

# - name: "Webhook IBM CIS Secrets : Copy all required secrets"
#   vars:
#     secret_name: "{{ item }}"
#   include_tasks: tasks/cert_manager_upgrade/copy_secret.yml
#   with_items: "{{ list_of_cis_secrets }}"

# - name: "Webhook IBM CIS Root CA : Copy cert-manager-webhook-ibm-cis-root-ca-issuer"
#   include_tasks: tasks/cert_manager_upgrade/copy_issuer.yml
#   vars:
#     source_issuer_name: "cert-manager-webhook-ibm-cis-root-ca-issuer"
#     source_issuer_secret_name: "cert-manager-webhook-ibm-cis-root-ca-certificate"
#     source_certificate_name: "cert-manager-webhook-ibm-cis-root-ca-certificate"

# - name: "Webhook IBM CIS Root CA : Copy cert-manager-webhook-ibm-cis-self-signed-issuer"
#   include_tasks: tasks/cert_manager_upgrade/copy_issuer.yml
#   vars:
#     source_issuer_name: "cert-manager-webhook-ibm-cis-self-signed-issuer"
#     source_issuer_secret_name: ""
#     source_certificate_name: "cert-manager-webhook-ibm-cis-serving-cert"

# After review with joao we only need these resources:
# secret/cis-api-key
# secret/cis-letsencrypt-production-account-key
# secret/cis-letsencrypt-staging-account-key
# TODO: We might want to uninstall cis webhook from old cert-manager ns and reinstall it in new ibm-common-services ns too
# currently, only its resources were migrated, but the cis-webhook deployment still runs on cert-manager ns

- name: "Webhook IBM CIS Secrets : Copy all required secrets"
  vars:
    secret_name: "{{ item }}"
  include_tasks: tasks/cert_manager_upgrade/copy_secret.yml
  with_items: 
    - cis-api-key
    - cis-letsencrypt-production-account-key
    - cis-letsencrypt-staging-account-key
