---

mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_namespace: "mas-{{ mas_instance_id }}-core"
mas_upgrade_supported_channels: ['maint86xdev', '8.6.x']

# cpd upgrade vars
# https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=35-upgrading-cloud-pak-data
# cpd35_meta_namespace: cpd-meta-ops
cpd_meta_namespace: ibm-common-services
cpd_services_namespace: cpd-meta-ops # reuse existing namespace that contains cpd v3.5 services
cpd_registry: cp.icr.io
cpd_registry_user: cp

# This is only used for cpd35, we have to use cp4d_hack_worker_nodes to set up the global image pull secret needed by cpd40
cpd_entitlement_key: "{{ lookup('env', 'CPD_ENTITLEMENT_KEY') }}"

cpd_storage_class: 'ibmc-file-gold-gid'
cpd_block_storage_class: 'ibmc-block-gold'
cpd_upgrade_supported_services:
  - db2wh
# we'll automatically lookup cpd 3.5 services to be upgraded
# cpd_services:
#   - db2wh

db2wh_upgrade_version: "11.5.7.0"
