---

mas_catalog_source: "{{ lookup('env', 'MAS_CATALOG_SOURCE') | default('ibm-operator-catalog', true) }}"
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"

mas_upgrade_supported_channels: ['maint86xdev', 8.6.x']
