---  
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibmc-file-custom-1000iops
parameters:
  billingType: hourly
  classVersion: "2"
  fsType: ext4
  sizeIOPSRange: |-
    [20-1999]Gi:[1000-1000]
  type: Performance
provisioner: ibm.io/ibmc-file
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
