kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ibmc-file-performance-gold-gid
provisioner: ibm.io/ibmc-file
parameters:
  billingType: hourly
  classVersion: '2'
  gidAllocate: 'true'
  iopsPerGB: '10'
  sizeRange: '[20-4000]Gi'
  type: Performance
reclaimPolicy: Delete
volumeBindingMode: Immediate
