---
- hosts: localhost
  any_errors_fatal: true

# 1. Deploy & configure the cluster
# -----------------------------------------------------------------------------
- name: Deploy ROKS cluster in IBM Cloud
  import_playbook: ocp/provision-roks.yml

- name: Login & configure OCP cluster
  import_playbook: ocp/configure-ocp.yml
  vars:
    cluster_type: roks
    ibmcloud_apikey: "{{ lookup('env', 'IBMCLOUD_APIKEY') }}"


# 2. Install MongoDb
# -----------------------------------------------------------------------------
- name: Install MongoDb (Community Edition)
  import_playbook: dependencies/install-mongodb-ce.yml
  vars:
    mongodb_storage_class: ibmc-block-gold
    mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"


# 3. Install SLS
# -----------------------------------------------------------------------------
- name: Install SLS
  import_playbook: sls/install-sls.yml
  vars:
    sls_storage_class: ibmc-file-gold-gid
    # Default to re-using the MAS entitlement key if we do not provide a specific one for SLS
    sls_entitlement_username: "{{ lookup('env', 'SLS_ENTITLEMENT_USERNAME') | default('cp', true) }}"
    sls_entitlement_key: "{{ lookup('env', 'SLS_ENTITLEMENT_KEY') | default(lookup('env', 'IBM_ENTITLEMENT_KEY'), true) }}"

    # Use the generated mongodb configuration
    mongodb_namespace: "{{ lookup('env', 'MONGODB_NAMESPACE') | default('mongoce', True) }}"
    mongodb_cfg_file: "{{ mas_config_dir }}/mongo-{{ mongodb_namespace }}.yml"

    # Bootstrap from the mas_config_dir
    bootstrap:
      license_id: "{{ lookup('env', 'SLS_LICENSE_ID') }}"
      registration_key: "{{ lookup('env', 'SLS_REGISTRATION_KEY') }}"
      entitlement_file: "{{mas_config_dir}}/entitlement.lic"


# 4. Install BAS
# -----------------------------------------------------------------------------
- name: Install BAS
  import_playbook: bas/install-bas.yml
  vars:
    # BAS Configuration
    bas_namespace: "{{ lookup('env', 'BAS_NAMESPACE') | default('ibm-bas', true) }}"
    bas_persistent_storage: "ibmc-file-bronze-gid"
    bas_meta_storage_class: "ibmc-block-bronze"

    bas_username: "{{ lookup('env', 'BAS_USERNAME') | default('basuser', true) }}"
    bas_password: "{{ lookup('env', 'BAS_PASSWORD') | default('', true) }}"

    bas_grafana_username: "{{ lookup('env', 'BAS_GRAFANA_USERNAME') | default('basuser', true) }}"
    bas_grafana_password: "{{ lookup('env', 'BAS_GRAFANA_PASSWORD') | default('', true) }}"
    bas_contact:
      email: "{{ lookup('env', 'BAS_CONTACT_MAIL') | default('', true) }}"
      firstName: "{{ lookup('env', 'BAS_CONTACT_FIRSTNAME') | default('', true) }}"
      lastName: "{{ lookup('env', 'BAS_CONTACT_LASTNAME') | default('', true) }}"

    # MAS Configuration
    mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
    mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"


# 5. Install Db2 CP4D service
# -----------------------------------------------------------------------------
- name: Install CP4D services
  import_playbook: cp4d/install-services-db2.yml
  vars:
    cpd_storage_class: ibmc-file-gold-gid


# 6. Create DB2 Warehouse instance in CP4D
# -----------------------------------------------------------------------------
- name: Install CP4D services & configure Db2
  import_playbook: cp4d/create-db2-instance.yml
  vars:
    cp4d_db2wh_instance_name: db2w-shared
    cp4d_meta_storage_class: ibmc-file-silver-gid
    cp4d_user_storage_class: ibmc-file-gold-gid
    cp4d_backup_storage_class: ibmc-file-gold-gid
    mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"
    mas_config_scope: system

# Temporary hack for Manage, because the operator is missing critical
# database configuration that requires manual intervention to set up.
- name: Db2 configuration hack for Manage
  import_playbook: mas/hack-manage-db2.yml


# 7. Install & configure MAS
# -----------------------------------------------------------------------------
- name: Install & configure MAS
  import_playbook: mas/install-suite.yml
  vars:
    mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"


# 8. Install & Configure Manage application
# -----------------------------------------------------------------------------
# Tip, to install the Health application in standalone mode, simply change
# mas_app_id to "health" in the following tasks, nothing else needs to be changed

- name: Install Manage
  import_playbook: mas/install-app.yml
  vars:
    mas_app_id: manage

# Note that this sample playbook is always assuming a workspace ID of masdev,
# this can easily be modified when creating your own playbooks.
- name: Configure Manage
  import_playbook: mas/configure-app.yml
  vars:
    mas_app_id: manage
    mas_workspace_id: masdev
