---
# This role will assume you have CloudPak for Data v3.5 installed in 'cpd-meta-ops' namespace
# and will perform an in-place upgrade to CloudPak for Data v4.0 where the CPD operators will be 
# deployed in 'ibm-common-services' namespace and the services will be deployed in existing 'cpd-meta-ops' namespace 

# - name: "Upgrade CloudPak for Data installation from v3.5 to v4.0"
#   include_tasks: tasks/cpd_upgrade/upgrade-cpd40.yml

# - name: Load variables
#   include_vars: vars/cpd40.yml

# - name: "Upgrade CloudPak for Data Services installation from v3.5 to v4.0"
#   include_tasks: tasks/cpd_upgrade/upgrade-services-cpd40.yml

- name: "Upgrade DB2 Warehouse instances"
  when: item == "db2wh"
  include_tasks: tasks/cpd_upgrade/upgrade-db2wh-instances.yml
  with_items: "{{ cpd_services }}"
