---
# This role will assume you have CloudPak for Data v3.5 installed in 'cpd-meta-ops' namespace
# and will perform an in-place upgrade to CloudPak for Data v4.0 where the CPD operators will be 
# deployed in 'ibm-common-services' namespace and the services will be deployed in existing 'cpd-meta-ops' namespace 

# 1. Upgrade CPD v3.5 to v4.0
# -----------------------------------------------------------------------------
# - name: "Upgrade CloudPak for Data installation from v3.5 to v4.0"
#   include_tasks: tasks/cpd_upgrade/upgrade-cpd40.yml

# 2. Upgrade CPD Services v3.5 to v4.0
# -----------------------------------------------------------------------------
# - name: Load variables
#   include_vars: vars/cpd40.yml

# - name: "Upgrade CloudPak for Data Services installation from v3.5 to v4.0"
#   include_tasks: tasks/cpd_upgrade/upgrade-services-cpd40.yml

# 3. Upgrade DB2 Warehouse Instances v3.5 to v4.0
# -----------------------------------------------------------------------------
- name: "Required for DB2 - Lookup 'norootsquash' DeamonSet is deployed"
  when: item == 'db2wh'
  community.kubernetes.k8s_info:
    api_version: apps/v1
    name: norootsquash
    namespace: kube-system
    kind: DaemonSet
  register: daemonset_output
  with_items: "{{ cpd_services }}"

- name: "Required for DB2 - Create 'norootsquash' DeamonSet"
  when: 
    - item == "db2wh"
    - daemonset_output.results[0].resources | length == 0
  include_tasks: tasks/cpd_upgrade/db2wh/setup_norootsquash.yml
  with_items: "{{ cpd_services }}"

- name: "Upgrade DB2 Warehouse instances"
  when: 
    - item == "db2wh"
  include_tasks: tasks/cpd_upgrade/db2wh/upgrade-db2wh-instances.yml
  with_items: "{{ cpd_services }}"
