apiVersion: cpd.ibm.com/v1
kind: Ibmcpd
metadata:
  name: ibmcpd-cr
  namespace: "{{ cpd_services_namespace }}"
spec:
  license:
    accept: true
    license: Standard
  # for some reason, cpd 3.5 install is using same storage class in both 'storageClass' and 'zenCoreMetadbStorageClass' vars i.e 'ibmc-file-gold-gid'
  # which is different to cpd 4.0, where 'storageClass' = 'ibmc-file-gold-gid' and 'zenCoreMetadbStorageClass' = 'ibmc-block-gold'
  # https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=35-upgrading-cloud-pak-data
  # TODO: use this command to auto set the storageClass property: oc get pvc user-home-pvc -o jsonpath='{.spec.storageClassName}'
  # TODO: use this command to auto set the zenCoreMetadbStorageClass property: oc get pvc datadir-zen-metastoredb-0 -o jsonpath='{.spec.storageClassName}'
  storageClass: "{{ cpd_storage_class }}"
  zenCoreMetadbStorageClass: "{{ cpd_storage_class }}" 
