---
- hosts: localhost
  any_errors_fatal: true
  vars:
    # MAS configuration
    mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"

    # MAS workspace configuration
    mas_workspace_id: "{{ lookup('env', 'MAS_WORKSPACE_ID') }}"

    # MAS application configuration
    mas_app_id: manage

    # Define what MAS components should be installed
    manage_components_default: {'base': {'version': 'latest'}}
    manage_components: "{{ lookup('env', 'MANAGE_COMPONENTS') | default(manage_components_default, true) }}"

  roles:
    - ibm.mas_devops.suite_app_configure
