---
- hosts: localhost
  any_errors_fatal: true
  vars:
    # Ensure these are kept in sync with the values used in cp4d/install-services-db2.yml
    cpd_version: "{{ lookup('env', 'CPD_VERSION') }}"
    cpd_meta_namespace: "{{ lookup('env', 'CPD_NAMESPACE') | default('cpd-meta-ops', true) }}"
    db2wh_instance_name: "{{ lookup('env', 'DB2WH_INSTANCE_NAME') }}"
  roles:
    - ibm.mas_devops.cp4d_db2wh_manage_hack
