---
- hosts: localhost
  any_errors_fatal: true
  roles:
    - ibm.mas_devops.suite_upgrade_check
    - ibm.mas_devops.cert_manager_upgrade
    # - ibm.mas_devops.cp4d_upgrade
    # - ibm.mas_devops.suite_upgrade
    # - ibm.mas_devops.ocp_upgrade
    # - ibm.mas_devops.sbo_upgrade
