---
# Define where AppConnect will be installed
appconnect_namespace: "{{ lookup('env', 'APPCONNECT_NAMESPACE') | default('ibm-app-connect', true) }}"
# v3.0 channel is used in MAS 8.7, v2.0 channel is used in older MAS versions
appconnect_channel: "{{ lookup('env', 'APPCONNECT_CHANNEL') | default('v3.0', true) }}"
appconnect_dashboard_name: "{{ lookup('env', 'APPCONNECT_DASHBOARD_NAME') | default('dashboard-12020r2', true) }}"
# L-KSBM-C87FU2 is the license id compatible with v3.0 channel (used in MAS 8.7), L-KSBM-C37J2R is compatible with v2.0 channel (used in MAS 8.6 and below)
appconnect_license_id: "{{ lookup('env', 'APPCONNECT_DASHBOARD_NAME') | default('L-KSBM-C87FU2', true) }}"
appconnect_storage_class: "{{ lookup('env', 'APPCONNECT_STORAGE_CLASS') }}"

# IBM entitlement key for AppConnect
# Default to re-using the IBM entitlement key if we do not provide a specific one for AppConnect
appconnect_entitlement_username: "{{ lookup('env', 'APPCONNECT_ENTITLEMENT_USERNAME') | default('cp', true) }}"
appconnect_entitlement_key: "{{ lookup('env', 'APPCONNECT_ENTITLEMENT_KEY') | default(lookup('env', 'IBM_ENTITLEMENT_KEY'), true) }}"
appconnect_registry: cp.icr.io

# MAS Configuration
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"
