dns_entries:
  - ""
  - "*"
  - "*.api.monitor"
  - "*.assist"
  - "*.health"
  - "*.home"
  - "*.hputilities"
  - "*.iot"
  - "*.manage"
  - "*.messaging.iot"
  - "*.monitor"
  - "*.predict"
  - "*.safety"
  - "*.visualinspection"
  - "cis.test.cert"
