---
# Note: This version of cert-manager is only intended for use with MAS v8.6 or earlier

- name: Install Cert Manager (Standalone)
  shell: |
    oc create namespace cert-manager
    oc apply -f https://github.com/jetstack/cert-manager/releases/download/v1.2.0/cert-manager.yaml
    oc get Deployment cert-manager -n cert-manager -o json | sed 's#cert-manager-controller:v1.2.0#cert-manager-controller@sha256:459a91307b9c7e06124c48236ddea1cc9ea0188cb66d1bbc6a30e78020445955#' | oc apply -f -
    oc get Deployment cert-manager-cainjector -n cert-manager -o json | sed 's#cert-manager-cainjector:v1.2.0#cert-manager-cainjector@sha256:5863cca33aec378f1d65678edf4af57f76b38977ac0e2f45a143131dbbf6818c#' | oc apply -f -
    oc get Deployment cert-manager-cainjector -n cert-manager -o json | sed 's#cert-manager-cainjector:v1.2.0#cert-manager-cainjector@sha256:5863cca33aec378f1d65678edf4af57f76b38977ac0e2f45a143131dbbf6818c#' | oc apply -f -
    oc get Deployment cert-manager-webhook -n cert-manager -o json | sed 's#cert-manager-webhook:v1.2.0#cert-manager-webhook@sha256:6ca391f059e04ebff77eb838a72d307c14dbc3a832995d54b7941fb8730eec66#' | oc apply -f -
