---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: mas-devops-cp4d-create-db2-instance
spec:
  params:
    - name: junit_suite_name
      type: string
      description: Optional name for the junit suite, used to enable save-junit-to-mongo.py
      default: ""
    - name: instance_name
      type: string
    - name: version
      type: string
    - name: tableorg
      type: string
    - name: meta_storage_class
      type: string  
    - name: meta_storage
      type: string
      default: "20"
    - name: user_storage_class
      type: string
    - name: user_storage
      type: string
      default: "100"
    - name: backup_storage_class
      type: string
    - name: backup_storage
      type: string
      default: "100"
    - name: logs_storage_class
      type: string
    - name: logs_storage
      type: string
      default: "100"
    - name: temp_storage_class
      type: string
    - name: temp_storage
      type: string
      default: "100"    
    - name: mas_config_scope
      type: string
    - name: mas_workspace_id
      type: string
      default: ""
    - name: mas_application_id
      type: string
      default: ""
  stepTemplate:
    env:
      - name: MAS_CONFIG_DIR
        value: /workspace/configs
      - name: JUNIT_SUITE_NAME
        value: $(params.junit_suite_name)
      - name: DB2WH_INSTANCE_NAME
        value: $(params.instance_name)
      - name: DB2WH_ADDON_VERSION
        value: $(params.version)
      - name: DB2WH_TABLE_ORG
        value: $(params.tableorg)
      - name: DB2WH_META_STORAGE_CLASS
        value: $(params.meta_storage_class)
      - name: DB2WH_META_STORAGE_SIZE_GB
        value: $(params.meta_storage)
      - name: DB2WH_USER_STORAGE_CLASS
        value: $(params.user_storage_class)
      - name: DB2WH_USER_STORAGE_SIZE_GB
        value: $(params.user_storage)
      - name: DB2WH_BACKUP_STORAGE_CLASS
        value: $(params.backup_storage_class)
      - name: DB2WH_BACKUP_STORAGE_SIZE_GB
        value: $(params.backup_storage)
      - name: DB2WH_LOGS_STORAGE_CLASS
        value: $(params.logs_storage_class)
      - name: DB2WH_LOGS_STORAGE_SIZE_GB
        value: $(params.logs_storage)
      - name: DB2WH_TEMP_STORAGE_CLASS
        value: $(params.temp_storage_class)
      - name: DB2WH_TEMP_STORAGE_SIZE_GB
        value: $(params.temp_storage)
      - name: MAS_CONFIG_SCOPE
        value: $(params.mas_config_scope)
      - name: MAS_WORKSPACE_ID
        value: $(params.mas_workspace_id)
      - name: MAS_APP_ID
        value: $(params.mas_application_id)
  steps:
    - name: cp4d-create-db2-instance
      command:
        - /opt/app-root/src/run-playbook.sh
        - /opt/app-root/lib/python3.8/site-packages/ansible_collections/ibm/mas_devops/playbooks/cp4d/create-db2-instance.yml
      image: quay.io/ibmmas/ansible-devops:latest
      workingDir: /workspace/configs

  workspaces:
    - name: configs
    - name: settings
