---
- hosts: localhost
  any_errors_fatal: true
  vars:
    cpd_services:
      # Watson Studio with Watson Machine Learning, Apache Spark, & Watson AI OpenScale capabilities enabled
      - wd
  roles:
    - ibm.mas_devops.cp4d_install
    - ibm.mas_devops.cp4d_install_services
