---
- hosts: localhost
  any_errors_fatal: true
  vars:
    # Cluster details
    # ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    cluster_name: "{{ lookup('env', 'CLUSTER_NAME') }}"
    cluster_type: "{{ lookup('env', 'CLUSTER_TYPE') }}"
    
    # MAS details
    # ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    mas87_default_channels: ['stable', 'm2dev87','m3dev87'] #temporarely solution: this will be used to tell playbooks the MAS 8.7 versions which should be using cpd 4.0 version
    mas_channel: "{{ lookup('env', 'MAS_CHANNEL') }}" #optional if 'cpd_version' is set
    
    # CP4D basic installation
    # ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    cpd_version: "{{ lookup('env', 'CPD_VERSION') }}" #optional if 'mas_channel' is set; supported cp4d versions: 'cpd35' or 'cpd40'
    cpd_registry: cp.icr.io
    cpd_registry_user: cp
    cpd_registry_password: "{{ lookup('env', 'CPD_ENTITLEMENT_KEY') }}"
    cpd_meta_namespace: "{{ lookup('env', 'CPD_NAMESPACE') | default('cpd-meta-ops', true) }}"
    cpd_storage_class: "{{ lookup('env', 'CPD_STORAGE_CLASS') }}"
    cpd_block_storage_class: "{{ lookup('env', 'CPD_BLOCK_STORAGE_CLASS') }}"

    # CP4D service configuration
    # -----------------------------------------------------------------------------------------------------------------
    cpd_services:
      # Watson Studio with Watson Machine Learning, Apache Spark, & Watson AI OpenScale capabilities enabled
      - wsl         # Required by Predict & HP Utilities
      - wml         # Required by Predict
      - spark       # Required by Predict
      - aiopenscale # Optional, used by Predict
  roles:
    - ibm.mas_devops.cp4d_install
    - ibm.mas_devops.cp4d_install_services
