---

# 1. Check for undefined properties that do not have a default
# -----------------------------------------------------------------------------
- name: "Assert that mas_instance_id is defined"
  assert:
    that:
      - mas_instance_id is defined
      - mas_instance_id != ""
    fail_msg: "mas_instance_id property is required"


# 2. Provide debug information
# -----------------------------------------------------------------------------
- name: "Debug information"
  debug:
    msg:
      - "Catalog source ............... {{ mas_catalog_source }}"
      - "Instance ID .................. {{ mas_instance_id }}"
      - "MAS namespace ................ {{ mas_namespace }}"


# 3. Check the existing installation
# -----------------------------------------------------------------------------
- name: "Check existing MAS installation"
  include_tasks: tasks/check_mas_install.yml


# 4. Check installed applications are compatible with MAS 8.7
# -----------------------------------------------------------------------------
- name: "Check installed MAS application compatability with MAS 8.7"
  include_tasks: tasks/check_mas_apps.yml


# 5. Upgrade to cert-manager v1.5 (IBM badged version)
# -----------------------------------------------------------------------------
# Note:
#   - This is not a requirement for MAS itself, but for CP4D v4
#   - MAS should not experience any outage during this upgrade, but certificates etc will
#     not be able to be updated during this process
#   - This is a cluster wide change, anything else in the using using cert-manager will
#     need to be updated to refer to the new namespace
- name: "Migrate cert-manager to IBM ibm-common-services"
  include_tasks: tasks/cert_manager_upgrade/upgrade.yml


# 6. Upgrade to CP4D v4
# -----------------------------------------------------------------------------
# Sorry, I have no idea how the CP4D upgrade should work, or what kinds of
# steps are required to migrate data from v3.5 to v4.0 and ensure everything
# continues to just work.
#
# Different namespaces are being used (cpd-meta-ops & cpd-services) so maybe we
# have both installed at the same time to migrate data?
#
# - How do we migrate a Db2 instance from CP4D v3.5 to v4?
# - How do we migrate <whatever> is being used in Watson Studio so that it
#   carries over into the v4 installation?
# - No upgrade for Discovery (when we tried to upgrade our development env
#   from CP4D 3.5 + WD 2.2.1 ---> CP4D 4.0 + WD 4.0 we met a lot of issues.
#   The process is quite complex and we met a lot of issues)

# 7. Upgrade the Subscription for ibm-mas to 8.7.x channel
# -----------------------------------------------------------------------------
# 7.1 Change subscription channel
- name: "Get installed version of ibm-mas"
  community.kubernetes.k8s:
    api_version: operators.coreos.com/v1alpha1
    name: "ibm-mas-operator"
    namespace: "{{ mas_namespace }}"
    kind: Subscription
    definition:
      spec:
        channel: "{{ mas_upgrade_target_channel }}"
    apply: true
  register: suite_sub_update

- debug: var=suite_sub_update


# 8. (optionally) Upgrade the application operators
# -----------------------------------------------------------------------------
# You don't need to upgrade the applications, you can leave them at the n-1
# supported versions from your prevoius MAS 8.6 installation if you wish.
- name: "Upgrade installed MAS application to new feature releases in MAS 8.7"
  include_tasks: tasks/upgrade_mas_apps.yml


# 9. (optionally) Upgrade OCP to v4.8
# -----------------------------------------------------------------------------
# MAS 8.7 is fully supported on both OCP 4.6, 4.8 (we can't support 4.7 because
# CP4D does not), however at some point before you eventually upgrade to MAS
# 8.8 you will need to upgrade OCP to v4.8
#
# We can only really automate the upgrade in ROKS, in other cluster types
# the user will need to perform the upgrade themselves (or implement additional
# provider support in this collection, we welcome all contributions)
#
# https://cloud.ibm.com/docs/openshift?topic=openshift-update#master

# 9.1 Upgrade to OCP 4.7
# ic oc cluster master update -c {{ cluster_name }} --version 4.7_openshift
# wait for master node upgrade to start
#    "masterStatus": "Version update in progress."
#    "masterState": "updating"
# wait for master node upgrade to complete
#    "masterStatus": "Ready"
#    "masterState": "deployed"
# ic oc worker update -c {{ cluster_name }} --version 4.7_openshift
# wait for worker node upgrade to complete

# Note: You are now running CP4D on an unsupported platform so may experience
# issues in the cluster until we complete the subsequent upgrade to OCP 4.8,
# sorry but there's no way to skip this intermediate upgrade step and CP4D
# are skipping OCP 4.7 support.

# 9.2 Upgrade to OCP 4.8
# ic oc cluster master update -c {{ cluster_name }} --version 4.8_openshift
# wait for master node upgrade to start
#    "masterStatus": "Version update in progress."
#    "masterState": "updating"
# wait for master node upgrade to complete
#    "masterStatus": "Ready"
#    "masterState": "deployed"
# ic oc worker update -c {{ cluster_name }} --version 4.8_openshift
# wait for worker node upgrade to complete


# 10. (optionally) Upgrade SBO to v1.0 - only if you upgraded to OCP v4.8
# -----------------------------------------------------------------------------
# MAS 8.7 fully supports both the preview and stable channels of the Red Hat
# service binding operator, however at some point before you eventually upgrade
# to MAS 8.8 you will need to upgrade to the stable channel.  The stable
# channel is not available in OCP 4.6
