---
# 1. Upgrade the Subscription for ibm-mas to 8.7.x channel
# -----------------------------------------------------------------------------
# 1.1 Change subscription channel
- name: "Update MAS 8.6 subscription to 8.7.x channel"
  community.kubernetes.k8s:
    api_version: operators.coreos.com/v1alpha1
    name: "ibm-mas-operator"
    namespace: "{{ mas_namespace }}"
    kind: Subscription
    definition:
      spec:
        channel: "{{ mas_upgrade_target_channel }}"
    apply: true
  register: suite_sub_update

# 1.2 Wait MAS 8.7.x to reconcile upgrade
# -----------------------------------------------------------------------------
- name: "Wait for Suite CR to finish reconciling upgrade to MAS 8.7.x successfully (60s delay)"
  community.kubernetes.k8s_info:
    api_version: v1
    name: "{{mas_instance_id}}"
    namespace: "{{mas_namespace}}"
    kind: Suite
  register: suite_cr_updated_result
  until:
    - suite_cr_updated_result.resources is defined
    - suite_cr_updated_result.resources | json_query('[*].status.conditions[?type==`Running`][].reason') | select ('match','Successful') | list | length == 1
    - suite_cr_updated_result.resources | json_query('[*].status.conditions[?type==`Failure`][].status') | select ('match','False') | list | length == 1
    - suite_cr_updated_result.resources | json_query('[*].status.conditions[?type==`Ready`][].reason') | select ('match','Ready') | list | length == 1
  retries: 60 # approx 60 minutes before we give up
  delay: 60 # 1 minute

# 1.3 Wait MAS 8.7.x to reconcile upgrade - Workspace CR
# -----------------------------------------------------------------------------
- name: "Wait for Suite Workspace CR to finish reconciling upgrade to MAS 8.7.x successfully (60s delay)"
  community.kubernetes.k8s_info:
    api_version: core.mas.ibm.com/v1
    kind: Workspace
    label_selectors:
      - mas.ibm.com/instanceId={{ mas_instance_id }}
  register: suite_ws_cr_updated_result
  until:
    - suite_ws_cr_updated_result.resources is defined
    - suite_ws_cr_updated_result.resources | json_query('[*].status.conditions[?type==`Running`][].reason') | select ('match','Successful') | list | length == 1
    - suite_ws_cr_updated_result.resources | json_query('[*].status.conditions[?type==`Failure`][].status') | select ('match','False') | list | length == 1
    - suite_ws_cr_updated_result.resources | json_query('[*].status.conditions[?type==`Ready`][].reason') | select ('match','Ready') | list | length == 1
  retries: 60 # approx 60 minutes before we give up
  delay: 60 # 1 minute

# 2. (optionally) Upgrade the application operators
# -----------------------------------------------------------------------------
# You don't need to upgrade the applications, you can leave them at the n-1
# supported versions from your previous MAS 8.6 installation if you wish.
- name: "Upgrade installed MAS application to new feature releases in MAS 8.7"
  include_tasks: tasks/upgrade_mas_apps.yml
