---
# Ansible can't support block retries, this is a relatively simple workaround
# to achieve the same thing
# https://github.com/ansible/ansible/issues/46203#issuecomment-556013701

# - name: debug vars
#   vars:
#     app_name: "{{ item }}"
#   debug: 
#     msg: 
#       - "{{ hostvars[inventory_hostname][item].apiVersion }}"
#       - "{{ hostvars[inventory_hostname][item].crdkind }}"
#       - "{{ hostvars[inventory_hostname][item].id }}"
#       - "mas-{{ mas_instance_id }}-{{ item }}"
#   with_items: "{{ mas_apps }}"

- name: 'wait : Wait until all apps are ready'
  block:
    - name: "wait : Set the retry count"
      set_fact:
        app_retry_count: "{{ 0 if app_retry_count is undefined else app_retry_count|int + 1 }}"
        apps_count: 0
        ready_apps_count: 0

    - name: "wait : Lookup app CRs"
      vars:
        app_name: "{{ item }}"
      community.kubernetes.k8s_info:
        api_version: "{{ hostvars[inventory_hostname][item].apiVersion }}"
        kind: "{{ hostvars[inventory_hostname][item].crdkind }}"
        name: "{{ mas_instance_id }}"
        namespace: "mas-{{ mas_instance_id }}-{{ item }}"
      register: app_cr_lookup
      until:
        - app_cr_lookup.resources is defined
        - app_cr_lookup.resources | length > 0
      with_items: "{{ mas_apps }}"

    # - debug:
    #     msg: "{{ app_cr_lookup}}"

    - name: "wait : Check if apps upgrade have been completed"
      set_fact:
        apps_count: "{{ apps_count|int + 1 }}"
        ready_apps_count: "{{ ready_apps_count|int + 1 if (item.resources is defined and item.resources | json_query('[*].status.conditions[?type==`Running`][].reason') | select ('match','Successful') | list | length == 1) else ready_apps_count|int}}"
      with_items: "{{ app_cr_lookup.results }}"
      loop_control:
        label: "{{ item.resources[0].kind }} CR status = {{ 'Successful' if (item.resources is defined and item.resources | json_query('[*].status.conditions[?type==`Running`][].reason') | select ('match','Successful') | list | length == 1) else 'In Progress' }}"

    - name: "wait : Fail if one or more apps upgrade still in progress..."
      when: ready_apps_count != apps_count
      fail:
        msg: "[{{ app_retry_count }}/300] {{ ready_apps_count }} of {{ apps_count }} apps are ready"
  rescue:
    - name: "wait : Give up after 300 attempts (approx 5 hours)"
      when: app_retry_count|int >= 300
      fail:
        msg: Timed out waiting for app operator to be ready

    - name: "wait : Wait for 1 minute before checking again"
      pause:
        minutes: 1

    - include_tasks: wait_for_app_upgrade.yml


# # 8. Wait for application to be ready
# # -----------------------------------------------------------------------------
# - name: "Wait for application to be ready (60s delay)"
#   community.kubernetes.k8s_info:
#     api_version: "{{ mas_app_api_version }}"
#     name: "{{ mas_instance_id }}"
#     namespace: "{{ mas_app_namespace }}"
#     kind: "{{ mas_app_kind }}"
#     wait: true
#     wait_condition:
#       status: "True"
#       type: Ready
#     wait_sleep: 30
#     wait_timeout: "{{ mas_app_install_timeout }}" # before we give up and fall back into the retry loop
#   register: app_cr_result
#   retries: "{{ mas_app_install_retries }}"
#   delay: 0
#   until:
#     - app_cr_result.resources is defined
#     - app_cr_result.resources | length > 0
#     - app_cr_result.resources | json_query('[*].status.conditions[?type==`Ready`][].status') | select ('match','True') | list | length == 1