galaxy_info:
  author: Alexandre Quinteiro (@alequint)
  description: Deploy Grafana Operator to analyse IBM Maximo Application Suite workload
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - grafana
    - prometheus
    - monitoring

dependencies:
  - role: ibm.mas_devops.ocp_verify
