---
# # Wait all apps start reconciling the upgrade
# - name: Wait MAS apps to start upgrade to 8.7 version
#   include_tasks: tasks/wait/wait_for_app_start_reconciling.yml

# Wait all apps to complete upgrade
- name: Wait MAS apps to complete upgrade to 8.7 version
  include_tasks: tasks/wait/wait_for_app_upgrade.yml

# After apps upgraded, wait for all apps workspace operators to reconcile
- name: 'Wait MAS apps workspace operators to reconcile the upgrade'
  include_tasks: tasks/wait/wait_for_app_ws_upgrade.yml

- debug:
    msg: "MAS Applications {{ mas_apps }} successfully upgraded to MAS 8.7 version!"