name: Build and Deploy Documentation
on:
  push:
    branches: [ master, manage-components ]
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          python -m pip install -q mkdocs
          mkdocs build --verbose --clean --strict

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: site

  build-ansible-collection:
    runs-on: ubuntu-latest
    steps:
      - name: Validate that the ansible collection lints successfully
        run: |
          python -m pip install -q ansible==2.10.3 yamllint
          yamllint -c $GITHUB_WORKSPACE/yamllint.yaml $GITHUB_WORKSPACE/ibm/mas_devops


# TODO: All of this!
# sudo: required
# language: python
# python: 3.8
# services:
#   - docker

# # Don't build on branches that match a semver string (ie the release tags that we create)
# branches:
#   except:
#     - /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/

# install:
#   - chmod u+x $TRAVIS_BUILD_DIR/build/bin/*.sh
#   - $TRAVIS_BUILD_DIR/build/bin/initbuild.sh

# script:
#   # 2. Build the Ansible collection
#   - $TRAVIS_BUILD_DIR/build/bin/build-collection.sh || travis_terminate 1
#   # 3. Install the Ansible collection in the container image
#   - cp $TRAVIS_BUILD_DIR/ibm/mas_devops/ibm-mas_devops-$(cat $TRAVIS_BUILD_DIR/.version).tar.gz $TRAVIS_BUILD_DIR/image/ansible-devops/ibm-mas_devops.tar.gz || travis_terminate 1
#   # 4. Build and push the docker image
#   - $TRAVIS_BUILD_DIR/build/bin/docker-build.sh -n ibmmas -i ansible-devops || travis_terminate 1
#   - $TRAVIS_BUILD_DIR/build/bin/docker-push.sh || travis_terminate 1
#   # 5. Build the tekton clustertasks
#   - $TRAVIS_BUILD_DIR/pipelines/bin/build-pipelines.sh || travis_terminate 1

# after_success:
#   # Publish a GitHub release with the ansible collection tgz as an assset
#   - $TRAVIS_BUILD_DIR/build/bin/git-release.sh $TRAVIS_BUILD_DIR/ibm/mas_devops/ibm-mas_devops-$(cat $TRAVIS_BUILD_DIR/.version).tar.gz $TRAVIS_BUILD_DIR/pipelines/ibm-mas_devops-clustertasks-$(cat $TRAVIS_BUILD_DIR/.version).tar.gz
