name: Build and Deploy Documentation
on:
  push:
    branches: [ master, manage-components ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          python -m pip install -q mkdocs
          mkdocs build --verbose --clean --strict

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: site
